.TH petal 1 2009-May "linux" "heatherly custom tools manual"

.SH NAME
themis \- enforce consistent system structure, security, and configuration

.SH SYNOPSIS
.B themis [URGENTS] [OPTIONS]

.SH DESCRIPTION (short version)
themis is light, small, and targeted configuration management system very
narrowly focused on filesystem structure and securty, and common configuration
specifically for heatherly-owned gentoo-linux systems.

.SH GREEK HERITAGE and NAMESAKE
themis-euboulos (well-counselled) is one of the twelve primary greek titans
and the titaness of divine law and order.  She acts as the divine voice
(themistes) who instructs mankind in the primal laws of justice, morality,
piety, hospitality, good governance, conduct of assembly, and equity.  after the
greek gods overthrew the titans, themis acted as one of zeus' first counselors.
themis and zeus bore many children including eunomia (order), dike (justice),
eirene (peace), as well as the horai (seasons) and the moirai (fates).
